table Canva
	lineageTag: bf6461f4-61d0-42b6-9213-d5b7a860886f

	column Column1
		dataType: string
		lineageTag: 00174ffb-51ba-4a5c-82ff-c3e21066037b
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 48bdbb61-a727-45dd-870c-70adbde12873
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 81eddb55-ad27-480a-baaf-32f16e30a083
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 1575de5a-6d64-4c24-8161-610987e2432c
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 218299fa-8539-41a3-a843-87f211c29eb8
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: bf363bb7-19f3-4d92-bdf2-8ab26c063933
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	partition Canva = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://senacnacional.sharepoint.com/sites/mapeamento-tecnologias/Documentos%20Compartilhados/Interlocutores/INTERLOCUTORES.xlsx"), null, true),
				    Canva_Sheet = Fonte{[Item="Canva",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Canva_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

