table EspacoDocente-ViewAno
	lineageTag: c7fa0e03-37d3-4c60-8ea6-0f2196740a8a

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 23b6a2cb-dd64-441c-833e-e5af6d683e18
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Views
		dataType: int64
		formatString: 0
		lineageTag: de66cc0d-a0a2-42fe-b614-1f990d973ce4
		summarizeBy: sum
		sourceColumn: Views

		annotation SummarizationSetBy = Automatic

	partition EspacoDocente-ViewAno = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjIwMlXSUTI0MjcwMFCK1QGLmAFFTE3BArEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t, #"Coluna 2" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", Int64.Type}, {"Coluna 2", Int64.Type}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Coluna 1", "Ano"}, {"Coluna 2", "Views"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

