table 'Espaço Docente - views'
	lineageTag: 06a8e2bc-bb1f-455a-9f9b-222a3664e3e0

	column Mês
		dataType: dateTime
		formatString: mmmm" de "yyyy
		lineageTag: c3e5626a-ffae-4dcd-8705-abff574d59c7
		summarizeBy: none
		sourceColumn: Mês
		sortByColumn: Númerico

		variation Variation
			isDefault
			relationship: c664e515-f882-4318-929b-f61473f1b527
			defaultHierarchy: LocalDateTable_e49b7efb-98ba-4b41-9828-498735b7a249.'Hierarquia de datas'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Visualizações
		dataType: int64
		formatString: 0
		lineageTag: e3716022-257a-496e-a94e-55d4c35757fe
		summarizeBy: sum
		sourceColumn: Visualizações

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Usuários
		dataType: int64
		formatString: 0
		lineageTag: 87da2c07-63f4-45fb-ba3f-4180d82ecdfc
		summarizeBy: sum
		sourceColumn: Usuários

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Númerico
		dataType: int64
		formatString: 0
		lineageTag: f9b03041-cef6-455f-971c-a35f334a74e0
		summarizeBy: sum
		sourceColumn: Númerico

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Espaço Docente - views' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\fabiano.araujo\Downloads\espaco_docente_mar26.xlsx"), null, true),
				    Tabela1_Table = Fonte{[Item="Tabela1",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela1_Table,{{"Mês", type text}, {"Visualizações", Int64.Type}, {"Usuários", Int64.Type}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Personalizar", each if [Mês] = "Janeiro" then 1 else if [Mês] = "Fevereiro" then 2 else if [Mês] = "Março" then 3 else if [Mês] = "Abril" then 4 else if [Mês] = "Maio" then 5 else if [Mês] = "Junho" then 6 else if [Mês] = "Julho" then 7 else if [Mês] = "Agosto" then 8 else if [Mês] = "Setembro" then 9 else if [Mês] = "Outubro" then 10 else if [Mês] = "Novembro" then 11 else if [Mês] = "Dezembro" then 12 else null),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Condicional Adicionada",{{"Personalizar", "Númerico"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Númerico", Int64.Type}})
				in
				    #"Tipo Alterado1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

