table 'KR 1 3'
	lineageTag: f27d69ad-74b3-49e4-a796-ebfeae278e55

	measure '% Iniciativa' = DIVIDE(SUM('KR 1 3'[Cursos Atendidos]), SUM('KR 1 3'[Cursos Totais]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9827a822-bcb9-4002-8504-44196da6dab3

		changedProperty = IsHidden

	measure '% Total KR 1.3' = DIVIDE(SUM('KR 1 3'[Cursos Atendidos]), SUM('KR 1 3'[Cursos Totais]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 568e8c7f-841c-42c8-9b9f-ff99fd56f141

		changedProperty = IsHidden

	measure 'Meta KR 1.3' = 1
		lineageTag: 8afa6d3d-c0c0-4944-9a05-deb966cd4fb2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta DO KR 1.3' = 0.9
		lineageTag: 4ba12dd5-b50a-4c9b-a489-90ae52f7fd3c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta DO KR 1.1' = 50
		lineageTag: ae45cc9b-37a4-406b-a899-fb6b90c136c8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Iniciativa
		dataType: string
		lineageTag: 31b711c6-ea6b-4b12-9dd8-c54126b515a8
		summarizeBy: none
		sourceColumn: Iniciativa

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cursos Atendidos'
		dataType: double
		formatString: 0
		lineageTag: dc62fce2-1175-4d51-a790-cd53ca715cac
		summarizeBy: sum
		sourceColumn: Cursos Atendidos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cursos Totais'
		dataType: int64
		formatString: 0
		lineageTag: 6de41be2-451c-49cd-aa35-9e9a8c8f565e
		summarizeBy: sum
		sourceColumn: Cursos Totais

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Meta KR'
		dataType: double
		lineageTag: e9fa88b7-2e42-4281-be7b-e2251d01eb80
		summarizeBy: sum
		sourceColumn: Meta KR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'KR 1 3' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://senacnacional.sharepoint.com/sites/mapeamento-tecnologias/Documentos%20Compartilhados/KR%201.3/KR%201.3.xlsx"), null, true),
				    #"KR 1.3_Sheet" = Fonte{[Item="KR 1.3",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"KR 1.3_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Iniciativa", type text}, {"Cursos Atendidos", Int64.Type}, {"Cursos Totais", Int64.Type}, {"Meta KR", type number}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado",11,0,Replacer.ReplaceValue,{"Cursos Atendidos"}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Valor Substituído",{"Iniciativa", "Cursos Atendidos", "Cursos Totais", "Meta KR"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Outras Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Linhas em Branco Removidas",14,11,Replacer.ReplaceValue,{"Cursos Atendidos"})
				in
				    #"Valor Substituído1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

