table 'KR 1 1'
	lineageTag: 83a32dd4-67cb-4f7f-a922-c6e473af95e7

	column usuCadAteMAtual
		dataType: double
		formatString: 0
		lineageTag: 5423b53e-8f40-4d41-9654-f4f1b2edea08
		summarizeBy: sum
		sourceColumn: usuCadAteMAtual

		annotation SummarizationSetBy = Automatic

	column UsuAtivos26
		dataType: double
		formatString: 0
		lineageTag: 774f0900-566f-430a-8969-b88de2f5efc5
		summarizeBy: sum
		sourceColumn: UsuAtivos26

		annotation SummarizationSetBy = Automatic

	partition 'KR 1 1' = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMrQwsVDSUTK1NDdXio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [usuCadAteMAtual = _t, UsuAtivos26 = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"usuCadAteMAtual", Int64.Type}, {"UsuAtivos26", Int64.Type}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado",1848,2654,Replacer.ReplaceValue,{"usuCadAteMAtual"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",5977,6318,Replacer.ReplaceValue,{"UsuAtivos26"})
				in
				    #"Valor Substituído1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

